dependencies:
  - base == 4.*
  - algolia
  - aeson
  - bytestring
  - containers
  - exceptions
  - monad-parallel
  - mtl
  - regex-base
  - regex-posix
  - safe-exceptions
  - scalpel
  - terminal-progress-bar
  - transformers
executables:
  scrawl:
    main: scrawl.hs
